services:
  db:
    image: postgres:17.0
    container_name: earthquake_db
    restart: always
    environment:
      POSTGRES_DB: earthquake_db
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d earthquake_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./earthquake-backend
      dockerfile: Dockerfile
    container_name: earthquake_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/earthquake_db
      SPRING_DATASOURCE_USERNAME: demo
      SPRING_DATASOURCE_PASSWORD: demo
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./earthquake-frontend
      dockerfile: Dockerfile
    container_name: earthquake_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
