spring.application.name=earthquake-backend
spring.datasource.url=jdbc:postgresql://localhost:5435/earthquake_db
spring.datasource.username=demo
spring.datasource.password=demo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
usgs.api.url=https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson
server.port=8081